// <auto-generated />
using System;
using FSH.Modules.MarketIntelligence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSH.Starter.Migrations.MSSQL.MarketIntelligence
{
    [DbContext(typeof(MarketIntelligenceDbContext))]
    [Migration("20260730202012_AddprevytdtoMonthlyActivity")]
    partial class AddprevytdtoMonthlyActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("marketintelligence")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Data.MonthlyActivitySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisclosureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PeriodAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PeriodEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PeriodFormula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodRowSequence")
                        .HasColumnType("int");

                    b.Property<decimal?>("PreviousYearToDateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rt")
                        .HasColumnType("tinyint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("TracingNo")
                        .HasColumnType("bigint");

                    b.Property<string>("YearEndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("YearToDateAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("YearToDateAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YearToDateFormula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearToDateRowSequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "PeriodEndDate")
                        .IsUnique();

                    b.ToTable("MonthlyActivitySummaries", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.Disclosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte?>("Ct")
                        .HasColumnType("tinyint");

                    b.Property<string>("ExcelUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<short?>("Ft")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExcel")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHtml")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPdf")
                        .HasColumnType("bit");

                    b.Property<bool>("HasXbrl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEstimate")
                        .HasColumnType("bit");

                    b.Property<short?>("Let")
                        .HasColumnType("smallint");

                    b.Property<string>("LetterCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("PublishDateTime")
                        .HasMaxLength(32)
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishDateTimeRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Rt")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SalesParseStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SalesParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentDateTime")
                        .HasMaxLength(32)
                        .HasColumnType("datetime2");

                    b.Property<string>("SentDateTimeRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TedanUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("TracingNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("XbrlUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("PublishDateTime");

                    b.HasIndex("TracingNo")
                        .IsUnique();

                    b.ToTable("Disclosures", "marketintelligence");
                });
#pragma warning restore 612, 618
        }
    }
}
