// <auto-generated />
using System;
using FSH.Modules.MarketIntelligence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSH.Starter.Migrations.MSSQL.MarketIntelligence
{
    [DbContext(typeof(MarketIntelligenceDbContext))]
    [Migration("20260827055805_AddFSortSymbolToPortfolioCompanyAliases")]
    partial class AddFSortSymbolToPortfolioCompanyAliases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("marketintelligence")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Data.MonthlyActivitySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisclosureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PeriodAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PeriodEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PeriodFormula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodRowSequence")
                        .HasColumnType("int");

                    b.Property<decimal?>("PreviousYearToDateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rt")
                        .HasColumnType("tinyint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("TracingNo")
                        .HasColumnType("bigint");

                    b.Property<string>("YearEndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("YearToDateAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("YearToDateAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YearToDateFormula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearToDateRowSequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "PeriodEndDate")
                        .IsUnique();

                    b.ToTable("MonthlyActivitySummaries", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.Disclosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte?>("Ct")
                        .HasColumnType("tinyint");

                    b.Property<string>("ExcelUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<short?>("Ft")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExcel")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHtml")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPdf")
                        .HasColumnType("bit");

                    b.Property<bool>("HasXbrl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEstimate")
                        .HasColumnType("bit");

                    b.Property<short?>("Let")
                        .HasColumnType("smallint");

                    b.Property<string>("LetterCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("PublishDateTime")
                        .HasMaxLength(32)
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishDateTimeRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportingTypeCode")
                        .HasColumnType("int");

                    b.Property<byte?>("Rt")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SalesParseStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SalesParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentDateTime")
                        .HasMaxLength(32)
                        .HasColumnType("datetime2");

                    b.Property<string>("SentDateTimeRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TedanUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("TracingNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("XbrlUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("PublishDateTime");

                    b.HasIndex("TracingNo")
                        .IsUnique();

                    b.ToTable("Disclosures", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.InvestmentPortfolioPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BeginningCost")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("BeginningMarketValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("BeginningQuantity")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("Capital")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("ChangeCost")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("ChangeMarketValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("ChangeQuantity")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<int?>("ChildCompanyId")
                        .HasColumnType("int");

                    b.Property<Guid>("DisclosureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("EndingCost")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingCostPerShare")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingMarketPrice")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingMarketValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingQuantity")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<string>("FSortName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("IncreaseDecrease")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NominalValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("OwnershipPercent")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ParentCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("PublishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawCompanyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RowSequence")
                        .HasColumnType("int");

                    b.Property<long>("TracingNo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChildCompanyId");

                    b.HasIndex("DisclosureId");

                    b.HasIndex("FSortName");

                    b.HasIndex("TracingNo");

                    b.HasIndex("ParentCompanyId", "PeriodEndDate");

                    b.ToTable("InvestmentPortfolioPositions", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.PortfolioCompanyAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FSortName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FSortSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FSortName");

                    b.HasIndex("FSortSymbol");

                    b.ToTable("PortfolioCompanyAliases", "marketintelligence");
                });
#pragma warning restore 612, 618
        }
    }
}
