// <auto-generated />
using System;
using FSH.Modules.MarketIntelligence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSH.Starter.Migrations.MSSQL.MarketIntelligence
{
    [DbContext(typeof(MarketIntelligenceDbContext))]
    [Migration("20260920053801_AddTsetmcMarketAnalytics")]
    partial class AddTsetmcMarketAnalytics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("marketintelligence")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Data.MonthlyActivitySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("DisclosureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PeriodAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PeriodEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PeriodFormula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodRowSequence")
                        .HasColumnType("int");

                    b.Property<decimal?>("PreviousYearToDateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rt")
                        .HasColumnType("tinyint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("TracingNo")
                        .HasColumnType("bigint");

                    b.Property<string>("YearEndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("YearToDateAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("YearToDateAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YearToDateFormula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearToDateRowSequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "PeriodEndDate");

                    b.HasIndex("Symbol", "PeriodEndDate")
                        .IsUnique();

                    b.ToTable("MonthlyActivitySummaries", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Data.Views.CompanyMasterView", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FSortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FSortSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.ToTable((string)null);

                    b.ToView("vw_CompanyMaster", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.CodalCompanyImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("CompanyType")
                        .HasColumnType("int");

                    b.Property<string>("IndustryGroupId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("IndustryId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Isic")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ReportingType")
                        .HasColumnType("int");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("CodalCompanyImport", "dbo");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.CodalIncrementalScheduleSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusyAfternoonMinutes")
                        .HasColumnType("int");

                    b.Property<int>("BusyMorningMinutes")
                        .HasColumnType("int");

                    b.Property<int>("BusyPeriodEndDay")
                        .HasColumnType("int");

                    b.Property<int>("EndHour")
                        .HasColumnType("int");

                    b.Property<int>("FridayMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MorningEndHour")
                        .HasColumnType("int");

                    b.Property<int>("NormalAfternoonMinutes")
                        .HasColumnType("int");

                    b.Property<int>("NormalMorningMinutes")
                        .HasColumnType("int");

                    b.Property<int>("StartHour")
                        .HasColumnType("int");

                    b.Property<int>("ThursdayBusyAfternoonMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ThursdayBusyMorningMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ThursdayNormalAfternoonMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ThursdayNormalMorningMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CodalIncrementalScheduleSettings", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.CompanyIndustry", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("IndustryGroupId")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<string>("IndustryId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("Isic")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("CompanyId");

                    b.HasIndex("IndustryId");

                    b.ToTable("CompanyIndustries", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.Disclosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte?>("Ct")
                        .HasColumnType("tinyint");

                    b.Property<string>("ExcelUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<short?>("Ft")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasAttachment")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExcel")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHtml")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPdf")
                        .HasColumnType("bit");

                    b.Property<bool>("HasXbrl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEstimate")
                        .HasColumnType("bit");

                    b.Property<short?>("Let")
                        .HasColumnType("smallint");

                    b.Property<string>("LetterCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("PublishDateTime")
                        .HasMaxLength(32)
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishDateTimeRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportingTypeCode")
                        .HasColumnType("int");

                    b.Property<byte?>("Rt")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SalesParseStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SalesParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentDateTime")
                        .HasMaxLength(32)
                        .HasColumnType("datetime2");

                    b.Property<string>("SentDateTimeRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TedanUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<long>("TracingNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("XbrlUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PublishDateTime");

                    b.HasIndex("TracingNo")
                        .IsUnique();

                    b.ToTable("Disclosures", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.ExternalSourceSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Key")
                        .IsUnique();

                    b.ToTable("ExternalSourceSettings", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.Industry", b =>
                {
                    b.Property<string>("IndustryId")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IndustryId");

                    b.ToTable("Industries", "dbo");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.Insights.Insight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Direction")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ImpactScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodEndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("CompanyId", "PeriodEndDate");

                    b.ToTable("Insights", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.Insights.SalesPerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableHistoryMonths")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsSixMonthAveragePercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsSixMonthHighPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsSixtyMonthAveragePercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsSixtyMonthHighPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsThreeMonthAveragePercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsThreeMonthHighPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsTwelveMonthAveragePercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsTwelveMonthHighPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsTwentyFourMonthAveragePercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentVsTwentyFourMonthHighPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MonthlyYoYGrowthPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PeriodEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("PreviousYearCurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PreviousYearRollingSixMonthAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PreviousYearRollingThreeMonthAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PreviousYearToDateAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RollingSixMonthAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RollingThreeMonthAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SixMonthAverage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SixMonthHigh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SixMonthHighPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SixMonthYoYGrowthPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SixtyMonthAverage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SixtyMonthHigh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SixtyMonthHighPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("ThreeMonthAverage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ThreeMonthHigh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThreeMonthHighPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("ThreeMonthYoYGrowthPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TwelveMonthAverage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TwelveMonthHigh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TwelveMonthHighPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("TwentyFourMonthAverage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TwentyFourMonthHigh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TwentyFourMonthHighPeriod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("YearToDateAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("YearToDateYoYGrowthPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodEndDate");

                    b.HasIndex("CompanyId", "PeriodEndDate")
                        .IsUnique();

                    b.ToTable("SalesPerformanceSnapshots", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.InvestmentPortfolioHoldingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntryDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ExitDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("HoldingAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ParentSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("HoldingAssetId");

                    b.HasIndex("ParentSymbol", "HoldingAssetId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("ParentSymbol", "IsActive");

                    b.HasIndex("ParentSymbol", "HoldingAssetId", "EntryDate")
                        .IsUnique();

                    b.ToTable("InvestmentPortfolioHoldingPeriods", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.InvestmentPortfolioPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AuditStatus")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("BeginningCost")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("BeginningMarketValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("BeginningQuantity")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("Capital")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("ChangeCost")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("ChangeMarketValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("ChangeQuantity")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<int?>("ChildCompanyId")
                        .HasColumnType("int");

                    b.Property<Guid>("DisclosureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("EndingCost")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingCostPerShare")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingMarketPrice")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingMarketValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<decimal?>("EndingQuantity")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<string>("FSortName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal?>("IncreaseDecrease")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NominalValue")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("OwnershipPercent")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ParentCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("PublishDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawCompanyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RowSequence")
                        .HasColumnType("int");

                    b.Property<byte>("SourceType")
                        .HasColumnType("tinyint");

                    b.Property<long>("TracingNo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChildCompanyId");

                    b.HasIndex("DisclosureId");

                    b.HasIndex("FSortName");

                    b.HasIndex("TracingNo");

                    b.HasIndex("ParentCompanyId", "PeriodEndDate");

                    b.ToTable("InvestmentPortfolioPositions", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.InvestmentPortfolioReportMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AuditStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("DisclosureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MetaTableCode")
                        .HasColumnType("int");

                    b.Property<int>("MetaTableId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PeriodEndToDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("RegisteredCapital")
                        .HasPrecision(28, 3)
                        .HasColumnType("decimal(28,3)");

                    b.Property<string>("ReportCompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReportSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SheetCode")
                        .HasColumnType("int");

                    b.Property<byte>("SourceType")
                        .HasColumnType("tinyint");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TitleFa")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("TracingNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnauthorizedCapital")
                        .HasPrecision(28, 3)
                        .HasColumnType("decimal(28,3)");

                    b.Property<string>("YearEndToDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DisclosureId");

                    b.HasIndex("TracingNo");

                    b.HasIndex("TracingNo", "SheetCode", "MetaTableId", "MetaTableCode")
                        .IsUnique();

                    b.ToTable("InvestmentPortfolioReportMetadata", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.PortfolioCompanyAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("FSortName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("FSortSymbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("HoldingAssetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsListed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Symbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FSortName");

                    b.HasIndex("FSortSymbol");

                    b.HasIndex("HoldingAssetId");

                    b.HasIndex("FSortName", "IsListed")
                        .IsUnique();

                    b.ToTable("PortfolioCompanyAliases", "marketintelligence");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.PortfolioHoldingAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FSortName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("ListedCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("UnlistedCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FSortName");

                    b.HasIndex("ListedCompanyId")
                        .IsUnique()
                        .HasFilter("[ListedCompanyId] IS NOT NULL");

                    b.HasIndex("Symbol");

                    b.HasIndex("UnlistedCompanyId")
                        .IsUnique()
                        .HasFilter("[UnlistedCompanyId] IS NOT NULL");

                    b.ToTable("PortfolioHoldingAssets", "marketintelligence", t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioHoldingAssets_CompanyId", "[UnlistedCompanyId] IS NOT NULL OR [ListedCompanyId] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.BenchmarkAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BenchmarkAssets", "marketintelligence");
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.BenchmarkDailyPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenchmarkAssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkAssetId", "TradeDate")
                        .IsUnique();

                    b.ToTable("BenchmarkDailyPrices", "marketintelligence");
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.DailyPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("BuyIndividualCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyIndividualValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyIndividualVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyInstitutionalCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyInstitutionalValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("BuyInstitutionalVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("ClosingPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("FirstPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("HighPrice")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("IndividualBuyerPower")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("InstitutionalNetFlow")
                        .HasColumnType("bigint");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<long>("LastPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("LowPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("RealMoneyFlow")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellIndividualCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellIndividualValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellIndividualVolume")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellInstitutionalCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellInstitutionalValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellInstitutionalVolume")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeCount")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.Property<long>("YesterdayPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "TradeDate")
                        .IsUnique();

                    b.ToTable("DailyPrices", "marketintelligence");
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.InstrumentShareChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<long>("NewShares")
                        .HasColumnType("bigint");

                    b.Property<long>("OldShares")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("InstrumentShareChanges", "marketintelligence");
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.InstrumentValuationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Eps")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ObservedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("PE")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<decimal?>("SalesPerShare")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.Property<decimal?>("SectorPE")
                        .HasPrecision(20, 6)
                        .HasColumnType("decimal(20,6)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "ObservedDate")
                        .IsUnique();

                    b.ToTable("InstrumentValuationHistory", "marketintelligence");
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.TsetmcInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InsCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("YVal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("InsCode")
                        .IsUnique();

                    b.HasIndex("Isin");

                    b.HasIndex("Symbol");

                    b.ToTable("TsetmcInstruments", "dbo");
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.CompanyIndustry", b =>
                {
                    b.HasOne("FSH.Modules.MarketIntelligence.Domain.Industry", null)
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.InvestmentPortfolioHoldingPeriod", b =>
                {
                    b.HasOne("FSH.Modules.MarketIntelligence.Domain.PortfolioHoldingAsset", null)
                        .WithMany()
                        .HasForeignKey("HoldingAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.MarketIntelligence.Domain.PortfolioCompanyAlias", b =>
                {
                    b.HasOne("FSH.Modules.MarketIntelligence.Domain.PortfolioHoldingAsset", null)
                        .WithMany()
                        .HasForeignKey("HoldingAssetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.BenchmarkDailyPrice", b =>
                {
                    b.HasOne("Modules.MarketIntelligence.Domain.BenchmarkAsset", null)
                        .WithMany()
                        .HasForeignKey("BenchmarkAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.DailyPrice", b =>
                {
                    b.HasOne("Modules.MarketIntelligence.Domain.TsetmcInstrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.InstrumentShareChange", b =>
                {
                    b.HasOne("Modules.MarketIntelligence.Domain.TsetmcInstrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.MarketIntelligence.Domain.InstrumentValuationHistory", b =>
                {
                    b.HasOne("Modules.MarketIntelligence.Domain.TsetmcInstrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
